---
- name: Update SSHD Config so we can double check it while the rest runs.
  template: src=sshdconfig.jinja2 dest=/etc/ssh/sshd_config
  notify: restart sshd

- name: Remove Wolfram Engine
  apt: name=wolfram-engine state=absent purge=yes

- name: Remove tons of X11 stuff no longer needed
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - scratch
    - penguinspuzzle
    - omxplayer
    - xserver*
    - x11*
    - xarchiver
    - xauth
    - xkb-data
    - console-setup
    - xinit
    - lightdm
    - lxde*
    - python-tk
    - python3-tk
    - gtk*
    - libgtk*
    - openbox
    - libxt*
    - lxpanel
    - gnome*
    - libqt*
    - libxcb*
    - libxfont*
    - lxmenu*
    - gvfs*
    - xdg-*
    - desktop*
    - shared-mime-info
    - gsfonts

- name: Check if packages need to be autoremoved
  command: apt-get --dry-run autoremove
  register: check_autoremove
  changed_when: False

- name: Autoremove unused packages
  command: apt-get -y autoremove
  when: "'packages will be REMOVED' in check_autoremove.stdout"

- name: Delete Python Games
  file: path=/home/pi/python_games state=absent

- name: Delete large test video
  file: path=/opt/vc/src/hello_pi/hello_video/test.h264 state=absent

- pause: prompt="SANITY CHECK!!! Everything from here on will add back to your server. Hit Ctrl+C now to abort and edit your roles/server_pi/tasks/main.yml file" seconds=15

- name: Upgrade System
  apt: update_cache=yes cache_valid_time=3600 upgrade=dist

- name: Create Dan's Account
  user: name=daniel shell=/bin/bash groups=adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,netdev,gpio,i2c,spi,input append=yes state=present password=$6$Y/yEFkcLXcuAaQ$EY3dBMxqPzh9gdt7qWBu4hC0YVOtIVfyvHev.7IGL5s.oCfwGn4fOABzSKtraENtJZ4Zbt9gRYedwDT.zjnRy0

- name: Add Dans local SSH keys (from my desktop /home/daniel/.ssh/*.pub to my pi user)
  authorized_key: user=daniel state=present key="{{ lookup('file', item) }}"
  with_fileglob:
    - /home/daniel/.ssh/*.pub

- name: Customize Dan's bashrc
  copy: src=/home/daniel/.bash_aliases owner=daniel group=daniel mode=640 dest=/home/daniel/.bash_aliases

- name: Add commonly needed programs
  apt: name={{ item }} state=latest
  with_items:
    - most
    - byobu
    - screen
    - htop
    - bmon
    - iftop
    - newsbeuter
    - unzip
    - unrar-free
    - p7zip-full
    - molly-guard
    - denyhosts
    - ufw

- name: Update UFW firewall to allow SSH access to local bogon ranges.
  ufw: rule=allow name=OpenSSH src={{ item }}
  with_items:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

- name: Enable UFW and have it start on boot
  ufw: state=enabled

- name: Harden SSH with denyhosts
  template: src=denyhosts.jinja2 dest=/etc/denyhosts.conf
  notify: restart denyhosts
